version: 2

run:
  timeout: 3m   # デフォルトより長めにしてタイムアウト防止
  tests: true   # テストコードも lint 対象にする

linters:
  enable:
    - govet         # Go標準の静的解析
    - staticcheck   # 強力な静的解析
    - errcheck      # エラー戻り値の未処理を検出

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck   # テストではエラーチェック必須にしない
  max-same-issues: 3   # 同じ種類の指摘は最大3つに抑える

formatters:
  enable:
    - gofmt

output:
  formats:
    colored-line-number: {}