version: "2"

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck

issues:
  max-same-issues: 3

formatters:
  enable:
    - gofmt

output:
  formats:
    text:
      path: stdout
      colors: true   # colored-line-number 相当