//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Edge defines model for Edge.
type Edge struct {
	Id string `json:"id"`

	// Source 接続元ノードID
	Source string `json:"source"`

	// Target 接続先ノードID
	Target string `json:"target"`
	Type   string `json:"type"`
}

// Healthz defines model for Healthz.
type Healthz struct {
	Message string `json:"message"`
}

// KanbanCardRef defines model for KanbanCardRef.
type KanbanCardRef struct {
	NodeId string `json:"nodeId"`
	PjId   string `json:"pjId"`
}

// KanbanColumns 各カラムごとのカード参照配列
type KanbanColumns struct {
	Backlog []KanbanCardRef `json:"backlog"`
	Doing   []KanbanCardRef `json:"doing"`
	Done    []KanbanCardRef `json:"done"`
	Todo    []KanbanCardRef `json:"todo"`
}

// KanbanIndex 本来 pjId -> nodeIdのSetだが、Setがないのでstring[]で代替
type KanbanIndex map[string][]string

// Minkan mindmap,kanban,作業中プロジェクトIDの状態
type Minkan struct {
	// CurrentPjId 作業中マインドマッププロジェクトのID
	CurrentPjId string `json:"currentPjId"`

	// KanbanColumns 各カラムごとのカード参照配列
	KanbanColumns KanbanColumns `json:"kanbanColumns"`

	// KanbanIndex 本来 pjId -> nodeIdのSetだが、Setがないのでstring[]で代替
	KanbanIndex KanbanIndex `json:"kanbanIndex"`

	// Projects pjID -> Project のマップ
	Projects Projects `json:"projects"`
}

// Node defines model for Node.
type Node struct {
	Data     NodeData `json:"data"`
	Id       string   `json:"id"`
	Position struct {
		X float32 `json:"x"`
		Y float32 `json:"y"`
	} `json:"position"`
	Type string `json:"type"`
}

// NodeComment defines model for NodeComment.
type NodeComment struct {
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`
}

// NodeData defines model for NodeData.
type NodeData struct {
	Comments []NodeComment `json:"comments"`
	IsDone   bool          `json:"isDone"`
	Label    string        `json:"label"`
	ParentId *string       `json:"parentId"`
}

// Project defines model for Project.
type Project struct {
	CreatedAt time.Time `json:"createdAt"`
	Edges     []Edge    `json:"edges"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	Nodes     []Node    `json:"nodes"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// Projects pjID -> Project のマップ
type Projects map[string]Project

// User defines model for User.
type User struct {
	DisplayName   *string              `json:"displayName"`
	Email         *openapi_types.Email `json:"email"`
	EmailVerified *bool                `json:"emailVerified"`

	// UserId アプリ内部のユーザーID（主キー）
	UserId openapi_types.UUID `json:"userId"`
}

// PostMinkanJSONRequestBody defines body for PostMinkan for application/json ContentType.
type PostMinkanJSONRequestBody = Minkan

// PutMinkanJSONRequestBody defines body for PutMinkan for application/json ContentType.
type PutMinkanJSONRequestBody = Minkan

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetHealthz request
	GetHealthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMinkan request
	GetMinkan(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostMinkanWithBody request with any body
	PostMinkanWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostMinkan(ctx context.Context, body PostMinkanJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutMinkanWithBody request with any body
	PutMinkanWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutMinkan(ctx context.Context, body PutMinkanJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteUsersMe request
	DeleteUsersMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersMe request
	GetUsersMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetHealthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMinkan(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMinkanRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostMinkanWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMinkanRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostMinkan(ctx context.Context, body PostMinkanJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMinkanRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutMinkanWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutMinkanRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutMinkan(ctx context.Context, body PutMinkanJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutMinkanRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteUsersMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteUsersMeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersMeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHealthzRequest generates requests for GetHealthz
func NewGetHealthzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMinkanRequest generates requests for GetMinkan
func NewGetMinkanRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/minkan")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostMinkanRequest calls the generic PostMinkan builder with application/json body
func NewPostMinkanRequest(server string, body PostMinkanJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostMinkanRequestWithBody(server, "application/json", bodyReader)
}

// NewPostMinkanRequestWithBody generates requests for PostMinkan with any type of body
func NewPostMinkanRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/minkan")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutMinkanRequest calls the generic PutMinkan builder with application/json body
func NewPutMinkanRequest(server string, body PutMinkanJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutMinkanRequestWithBody(server, "application/json", bodyReader)
}

// NewPutMinkanRequestWithBody generates requests for PutMinkan with any type of body
func NewPutMinkanRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/minkan")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteUsersMeRequest generates requests for DeleteUsersMe
func NewDeleteUsersMeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersMeRequest generates requests for GetUsersMe
func NewGetUsersMeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetHealthzWithResponse request
	GetHealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthzResponse, error)

	// GetMinkanWithResponse request
	GetMinkanWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMinkanResponse, error)

	// PostMinkanWithBodyWithResponse request with any body
	PostMinkanWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostMinkanResponse, error)

	PostMinkanWithResponse(ctx context.Context, body PostMinkanJSONRequestBody, reqEditors ...RequestEditorFn) (*PostMinkanResponse, error)

	// PutMinkanWithBodyWithResponse request with any body
	PutMinkanWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutMinkanResponse, error)

	PutMinkanWithResponse(ctx context.Context, body PutMinkanJSONRequestBody, reqEditors ...RequestEditorFn) (*PutMinkanResponse, error)

	// DeleteUsersMeWithResponse request
	DeleteUsersMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteUsersMeResponse, error)

	// GetUsersMeWithResponse request
	GetUsersMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUsersMeResponse, error)
}

type GetHealthzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Healthz
}

// Status returns HTTPResponse.Status
func (r GetHealthzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMinkanResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Minkan
}

// Status returns HTTPResponse.Status
func (r GetMinkanResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMinkanResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostMinkanResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Minkan
}

// Status returns HTTPResponse.Status
func (r PostMinkanResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostMinkanResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutMinkanResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Minkan
}

// Status returns HTTPResponse.Status
func (r PutMinkanResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutMinkanResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteUsersMeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteUsersMeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteUsersMeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersMeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *User
}

// Status returns HTTPResponse.Status
func (r GetUsersMeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersMeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetHealthzWithResponse request returning *GetHealthzResponse
func (c *ClientWithResponses) GetHealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthzResponse, error) {
	rsp, err := c.GetHealthz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthzResponse(rsp)
}

// GetMinkanWithResponse request returning *GetMinkanResponse
func (c *ClientWithResponses) GetMinkanWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMinkanResponse, error) {
	rsp, err := c.GetMinkan(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMinkanResponse(rsp)
}

// PostMinkanWithBodyWithResponse request with arbitrary body returning *PostMinkanResponse
func (c *ClientWithResponses) PostMinkanWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostMinkanResponse, error) {
	rsp, err := c.PostMinkanWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMinkanResponse(rsp)
}

func (c *ClientWithResponses) PostMinkanWithResponse(ctx context.Context, body PostMinkanJSONRequestBody, reqEditors ...RequestEditorFn) (*PostMinkanResponse, error) {
	rsp, err := c.PostMinkan(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMinkanResponse(rsp)
}

// PutMinkanWithBodyWithResponse request with arbitrary body returning *PutMinkanResponse
func (c *ClientWithResponses) PutMinkanWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutMinkanResponse, error) {
	rsp, err := c.PutMinkanWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutMinkanResponse(rsp)
}

func (c *ClientWithResponses) PutMinkanWithResponse(ctx context.Context, body PutMinkanJSONRequestBody, reqEditors ...RequestEditorFn) (*PutMinkanResponse, error) {
	rsp, err := c.PutMinkan(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutMinkanResponse(rsp)
}

// DeleteUsersMeWithResponse request returning *DeleteUsersMeResponse
func (c *ClientWithResponses) DeleteUsersMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteUsersMeResponse, error) {
	rsp, err := c.DeleteUsersMe(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteUsersMeResponse(rsp)
}

// GetUsersMeWithResponse request returning *GetUsersMeResponse
func (c *ClientWithResponses) GetUsersMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUsersMeResponse, error) {
	rsp, err := c.GetUsersMe(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersMeResponse(rsp)
}

// ParseGetHealthzResponse parses an HTTP response from a GetHealthzWithResponse call
func ParseGetHealthzResponse(rsp *http.Response) (*GetHealthzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Healthz
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetMinkanResponse parses an HTTP response from a GetMinkanWithResponse call
func ParseGetMinkanResponse(rsp *http.Response) (*GetMinkanResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMinkanResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Minkan
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostMinkanResponse parses an HTTP response from a PostMinkanWithResponse call
func ParsePostMinkanResponse(rsp *http.Response) (*PostMinkanResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostMinkanResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Minkan
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParsePutMinkanResponse parses an HTTP response from a PutMinkanWithResponse call
func ParsePutMinkanResponse(rsp *http.Response) (*PutMinkanResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutMinkanResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Minkan
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteUsersMeResponse parses an HTTP response from a DeleteUsersMeWithResponse call
func ParseDeleteUsersMeResponse(rsp *http.Response) (*DeleteUsersMeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteUsersMeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetUsersMeResponse parses an HTTP response from a GetUsersMeWithResponse call
func ParseGetUsersMeResponse(rsp *http.Response) (*GetUsersMeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersMeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ヘルスチェック用
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// mindmap,kanban,作業中プロジェクトIDの取得
	// (GET /minkan)
	GetMinkan(w http.ResponseWriter, r *http.Request)
	// mindmap,kanban,作業中プロジェクトIDの新規登録
	// (POST /minkan)
	PostMinkan(w http.ResponseWriter, r *http.Request)
	// mindmap,kanban,作業中プロジェクトIDの更新
	// (PUT /minkan)
	PutMinkan(w http.ResponseWriter, r *http.Request)
	// ユーザーの退会処理
	// (DELETE /users/me)
	DeleteUsersMe(w http.ResponseWriter, r *http.Request)
	// ログインユーザー情報を取得（初回は自動登録）
	// (GET /users/me)
	GetUsersMe(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMinkan operation middleware
func (siw *ServerInterfaceWrapper) GetMinkan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMinkan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostMinkan operation middleware
func (siw *ServerInterfaceWrapper) PostMinkan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostMinkan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutMinkan operation middleware
func (siw *ServerInterfaceWrapper) PutMinkan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutMinkan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUsersMe operation middleware
func (siw *ServerInterfaceWrapper) DeleteUsersMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUsersMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersMe operation middleware
func (siw *ServerInterfaceWrapper) GetUsersMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc("GET "+options.BaseURL+"/minkan", wrapper.GetMinkan)
	m.HandleFunc("POST "+options.BaseURL+"/minkan", wrapper.PostMinkan)
	m.HandleFunc("PUT "+options.BaseURL+"/minkan", wrapper.PutMinkan)
	m.HandleFunc("DELETE "+options.BaseURL+"/users/me", wrapper.DeleteUsersMe)
	m.HandleFunc("GET "+options.BaseURL+"/users/me", wrapper.GetUsersMe)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYW1PbRhv+K579vovvm1GwKelM6jsad1JPJomnp5uEi8VajECn6JAJZTyDpJCYBAKT",
	"SSAHCDnjkGLSppOhg5v8mEUyvuIvdHYl2UJaY7ul6UVvHEXafQ/P8+z7vss0KCqSqshINnSQnQZ6cRxJ",
	"kD5+xZcQ+VfVFBVphoDoW4Env8aUikAW6IYmyCVQ5oCumFqRLueRXtQE1RAUGWSBd/tl4/1Dd9bBzm3s",
	"1LEzl88BLrnfgFoJGZ33V7rtpy8SgZU5oKHLpqAhHmQvkuCDpa2IW65HWlaV0QlUNIjVrxEUjfEfkyhI",
	"SNdhqQeP4UKW9bNQHoXyaajx36AxYgryvEDyhmIh4m0MijriYgHICo/ybCrUCeaHWGB0FRfaOSI8RTQl",
	"We8a3mHa3KVr2H6DndfYeYKtu9iqYqtG3xAK3UW7MbvRnF1wKysgntkoLE6KSolqzUASffdfjQAE/pNu",
	"izUdKDV9GMWWFADUNDhF/s8rJP9jNCej47NmKLxyXNZiDIdABk5CIIIMOjOel3l0tTPfkVg7nMIgHg6Y",
	"snDZRHl/uaGZqBzXibf6k7f2MkXEmDpxycxkhlDKlyS2at8iA1tPsDWPZyz6PI+tTWxdI1KyNnyvF0ew",
	"tbG3+9x79BEwMjonyJNQTpYVSZB5CarcJM2Y2/t91Xu5tbezhZ0V7GxhewfbG9jexk4ln8NWrXHzvTd7",
	"KyHVoqlpSDYKwYE77CJi8zG2X2DnHXbmyLPjUC9xR9iqsUvbZPwc9iCRYHFrd4vT7nv9pWWaK4Gxq8tC",
	"uC4uwCg8EXOHY4rnx9LleYVndCIeGrBbbGRnjqwrc506l6rogk9Z3MHVyHrZlEaRRtZPMd7GEidZTTEz",
	"6b9N0SwjUXbC57QiSUg2+mwjRUU2gl0JYIoaggbih+nXMUWToAGyJB50whAkxJKqwPeYXOg36qVTZrmA",
	"53jkNF+95+IZBYlRiAU9FxT24MuooogIyuSbCEeRyBYPJAr3j79siiIcFZFf6rguMPg2W365dkIsHIIz",
	"1i+7/TOI+BLqHVM6IrLAZB81GUqI/UHhUX9MsryaKt9fuixl0hjDiEI8ojKN+jmCKv2oDtpDOQWJXqlO",
	"5HOtJhmsSpFeGPYUVgP8Xkcao3QKuirCqfMBH12UywEkQUE8hKr/hutx6w9IE8YEdNQxiRw3U0caq6Ni",
	"+xltm5vu9dmmQydK5xWZKO332Knncwf1yt7OLra3sFM/qM8Brh2uabZrakf+A79JUslCQR5TOs4R2Nn1",
	"m2fqf/7E8f/UcCE/kDqjKCURpS7kc6dT2L7jVl437laxtYKt9f3Nhf1qnbycW/AWl+iEvIJnrGhK7cmZ",
	"NUIc1G/Rifoddpbo7w268SO27zRqTxtL1wcuySRnwSBggzNKSqKxnRgu5FPfIUkVoUGkfgVpup/N4EBm",
	"IEMYUFQkQ1UAWTA0kBkYIv0HGuNUOunx9p0ouLERZUECCCENnEFGeG0i8OqqIuu+6j7LZGI9B6qqKBTp",
	"3vSE7vdg/xx0OyWhC8rNYU4ay7ebMw+9ypJ7c50k83lmKEmcT8XezoK7uE2FoJuSBLUpIjPnPnbeYPs3",
	"7FhkOnMcbG837lbpVbGkE6WE3kfIzrTUGjKZV1g65731+XM/zGPrjbu47H5YwdY9bM9jm8yVCQiDwfVv",
	"RDDwwADwwlkC28nMYDKXULVVerWr++tOsnIOxWjNe6ubjQe7zflfYjj3OYP7oEVICBIY8Wc4g8XxWhR7",
	"74Ht1tb3n84n8C4oehTwyybSjS8VfuoTYO1W1rzVdR+fFmggWpeCe1NMB4OfIDZv+e3+q0XCS2WpfZx6",
	"18UXXXSx8oycha377mr1r0nDDzQQGVsgJqNSFcx/inXv0a/e8lvSC/qg/N979H24WMyS8kvatp6Wgj8+",
	"ishArKAiXbUdYBVba9iq+QU82kDduZvNBy8ShSJHzZOZSj+HksWZgYa39dzd2SE69y32jG6sJUWHglpz",
	"Zmav/tC98aqxdD2CCo2Lyr1TY+4Y+fFpiw6cDGVFU/CcWffJz38ai3ZJTxol3NFGcVCvuJU199FjbG3v",
	"39h0b93zlegPhnHIqAukkVEIZC9OA1MTQRaMG4aaTadFpQjFcUU3sqcypzLpK4OgPNIyMR3calozQZk7",
	"SnzN5WfNmefDhXx41cgGMSS3nQtmS6vqz5YtfTJshCd6pPxHAAAA//95N7Bv0RcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
